### ISSUE TITLE
Karabiner-Elements endlessly getting  virtual-hid-device-service-client - connect_failed 

### ISSUE THREAD

**Issue by bomtailey** [pqrs-org/Karabiner-DriverKit-VirtualHIDDevice#10]
Did installation steps. After sudo ./build/Release/virtual-hid-device-service-client which produced:

connected
driver_loaded 1
driver_version_matched 1
virtual_hid_keyboard_ready 1
virtual_hid_pointing_ready 1

but never completed so I stopped it. Now when I run Karabiner-Elements the log shows an unending report of
[Info] [grabber] virtual-hid-device-service-client_ connect_failed: No such file or directory

I've installed this before and gotten it working but with the latest update on Big Sur 11.0 20A5395g K-E stopped working and I've been trying to get it working again. Frankly, I don't really understand all the Mac actions and configurations so finding my missteps would be very helpful.
Thanks

**Comment by bomtailey** [comment]
Just a follow-up on previous note. I've de-installed and re-installed several times. I never see the system preferences keyboard display shown on the GitHub page, no keyboard choices are shown. The response I get from executing the examples is shown below. Also the log messages when Karabiner-Elements is executed. Any suggestions as to where I'm going wrong? This used to install without problems.
Thanks

<img width="278" alt="Karabiner virtualHID driver example results" src="https://user-images.githubusercontent.com/17606064/97053948-91401e80-151f-11eb-9f80-ed34741bed07.png">
<img width="1080" alt="Karabiner grabber connect fail" src="https://user-images.githubusercontent.com/17606064/97053951-9309e200-151f-11eb-836c-a269daa91eed.png">

**Comment by bomtailey** [comment]
One more thing I forgot to add. When I run Karabiner-DriverKit-VirtualHIDDeviceClient I get the result below. I got it even when the EventViewer detected the side button of my MS Sculpt Comfort Mouse (which it no longer does). In addition, somehow in devices a second version of the mouse is declared, with "Apple" as the manufacturer. I have no idea where that is coming from.

 
<img width="554" alt="Karabiner-DriverKit-VirtualHIDDeviceClient results" src="https://user-images.githubusercontent.com/17606064/97054853-53dc9080-1521-11eb-974c-189ea184c9f8.png">

**Comment by tekezo** [comment]
> but never completed so I stopped it.
It is intended behavior.
https://github.com/pqrs-org/Karabiner-DriverKit-VirtualHIDDevice/blob/master/client/examples/virtual-hid-device-service-client/src/main.cpp#L138-L142

> Now when I run Karabiner-Elements the log shows an unending report of
Karabiner-Elements depends on the bundled driver.
The current Karabiner-DriverKit-VirtualHIDDevice does not work with Karabiner-Elements v13.0.0.

The latest beta version of Karabiner-Elements includes the latest driver. Please confirm it.

How to upgrade Karabiner-Elements:

Since you are upgrading the drivers manually, you have to to uninstall the driver before updating Karabiner-Elements.
https://github.com/pqrs-org/Karabiner-DriverKit-VirtualHIDDevice#uninstallation

After uninstallation, press "Check for beta updates" button.
<https://pqrs.org/osx/karabiner/document.html#check-for-updates>


> When I run Karabiner-DriverKit-VirtualHIDDeviceClient I get the result below.
Karabiner-DriverKit-VirtualHIDDeviceClient v0.20.0 is not compatible the current driver.

**Comment by bomtailey** [comment]
Thank you so much, everything works perfectly again and I really love the functionality.
